In [22]:
import numpy as np
import pandas as pd
from sklearn.metrics import precision_score,recall_score,f1_score

In [6]:
df = pd.read_csv('train.csv')

In [7]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X= df.iloc[:,1:]
Y= df.iloc[:,0]

In [11]:
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2,random_state=3)

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [14]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()
clf1.fit(X_train,Y_train)
clf2.fit(X_train,Y_train)

/Users/parajulitilak/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [15]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(Y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(Y_test,y_pred2))

Accuracy of Logistic Regression 0.9153571428571429
Accuracy of Decision Trees 0.856547619047619

In [20]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(Y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  781    0    3    1    1    5    7    1    5    2
1    0  863    4    3    1    2    2    5    5    1
2    8   15  722   12   10    5    6   12   18    2
3    1    2   24  768    0   29    1    9   18    8
4    2    3   11    1  762    0    8    3    7   35
5    9    4    2   32    7  685   19    6   25    1
6   12    3    6    0    7   11  784    1    2    0
7    1    3   15    8    2    1    2  843    2   32
8   11   19   12   24    6   25    6    3  700    9
9    2    3    1    7   30    8    0   24   10  781

In [21]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(Y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  733    1   14    8    4   10   12    3   13    8
1    0  843   10    4    5    8    2    6    6    2
2   11   17  679   28   12    6   10   10   29    8
3    6    7   22  711    8   41    7   14   31   13
4    2    7   13   13  710   16    9   10   10   42
5   16    8    6   55   13  613   28    7   31   13
6   15    5   14    8   16   15  733    1   15    4
7    2    9   23   25    6    4    0  816    7   17
8   12   16   22   40   25   26   15   14  623   22
9    1    0    5   21   38    9    2   41   15  734

In [31]:
precision_score(Y_test,y_pred1,average=None) #here none gives precision of each class seperately

array([0.94437727, 0.9431694 , 0.9025    , 0.89719626, 0.92251816,
       0.88845655, 0.93892216, 0.92943771, 0.88383838, 0.89667049])

In [32]:
precision_score(Y_test,y_pred1,average='weighted')

0.9150118142436056

In [33]:
recall_score(Y_test,y_pred1,average='weighted')

0.9153571428571429

In [29]:
f1_score(Y_test,y_pred1,average='weighted')

0.9151048914530174

In [26]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.94      0.97      0.96       806
           1       0.94      0.97      0.96       886
           2       0.90      0.89      0.90       810
           3       0.90      0.89      0.90       860
           4       0.92      0.92      0.92       832
           5       0.89      0.87      0.88       790
           6       0.94      0.95      0.94       826
           7       0.93      0.93      0.93       909
           8       0.88      0.86      0.87       815
           9       0.90      0.90      0.90       866

    accuracy                           0.92      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.92      0.92      0.92      8400